import {
  Table, Column, Model, DataType, ForeignKey, BelongsTo
} from 'sequelize-typescript';
import { Tenant } from '@modules/tenancy/tenant.model';
import { Patient } from '@modules/patients/patient.model';
import { Doctor } from '@modules/doctors/doctor.model';
import { Appointment } from '@modules/appointments/appointment.model';

export enum TelemedicineProvider {
  DAILY_CO = 'daily_co',
  JITSI = 'jitsi',
  TWILIO = 'twilio',
  WEBRTC = 'webrtc',
  EXTERNAL = 'external'
}

export enum TelemedicineStatus {
  SCHEDULED = 'scheduled',
  ACTIVE = 'active',
  COMPLETED = 'completed',
  CANCELLED = 'cancelled'
}

/**
 * A persisted video-consultation session. The video-provider integration is
 * pluggable: `room_name` / `join_url` / `host_url` are generated by the
 * configured provider (a stub deterministic-room generator by default) so the
 * lifecycle and records exist independently of any specific vendor SDK.
 */
@Table({
  tableName: 'telemedicine_sessions',
  timestamps: true,
  underscored: true,
  paranoid: true,
  freezeTableName: true,
  indexes: [
    { fields: ['tenant_id'] },
    { fields: ['doctor_id'] },
    { fields: ['patient_id'] },
    { fields: ['appointment_id'] },
    { fields: ['status'] },
    { fields: ['scheduled_at'] }
  ]
})
export class TelemedicineSession extends Model {
  @Column({ type: DataType.UUID, defaultValue: DataType.UUIDV4, primaryKey: true })
  override id!: string;

  @ForeignKey(() => Appointment)
  @Column({ type: DataType.UUID, allowNull: true })
  appointment_id?: string;

  @BelongsTo(() => Appointment)
  appointment?: Appointment;

  @ForeignKey(() => Doctor)
  @Column({ type: DataType.UUID, allowNull: false })
  doctor_id!: string;

  @BelongsTo(() => Doctor)
  doctor?: Doctor;

  @ForeignKey(() => Patient)
  @Column({ type: DataType.UUID, allowNull: false })
  patient_id!: string;

  @BelongsTo(() => Patient)
  patient?: Patient;

  @Column({ type: DataType.ENUM(...Object.values(TelemedicineProvider)), allowNull: false, defaultValue: TelemedicineProvider.WEBRTC })
  provider!: TelemedicineProvider;

  @Column({ type: DataType.STRING(200), allowNull: false })
  room_name!: string;

  // Patient-facing join link.
  @Column({ type: DataType.STRING(500), allowNull: true })
  join_url?: string;

  // Clinician-facing host/moderator link.
  @Column({ type: DataType.STRING(500), allowNull: true })
  host_url?: string;

  @Column({ type: DataType.ENUM(...Object.values(TelemedicineStatus)), allowNull: false, defaultValue: TelemedicineStatus.SCHEDULED })
  status!: TelemedicineStatus;

  @Column({ type: DataType.DATE, allowNull: true })
  scheduled_at?: Date;

  @Column({ type: DataType.DATE, allowNull: true })
  started_at?: Date;

  @Column({ type: DataType.DATE, allowNull: true })
  ended_at?: Date;

  @Column({ type: DataType.INTEGER, allowNull: true, comment: 'Session length in minutes, set on end' })
  duration_minutes?: number;

  @Column({ type: DataType.STRING(500), allowNull: true })
  recording_url?: string;

  @Column({ type: DataType.TEXT, allowNull: true })
  notes?: string;

  @ForeignKey(() => Tenant)
  @Column({ type: DataType.UUID, allowNull: false })
  tenant_id!: string;

  @BelongsTo(() => Tenant)
  tenant?: Tenant;

  declare createdAt: Date;
  declare updatedAt: Date;
}
