export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  DOCTOR: 'doctor',
  NURSE: 'nurse',
  RECEPTIONIST: 'receptionist',
  LAB_TECH: 'lab_technician',
  BILLING: 'billing_staff',
  PATIENT: 'patient'
};

export const PERMISSIONS = {
  // Queue Management
  QUEUE_CHECK_IN: 'queue:check_in',
  QUEUE_VIEW: 'queue:view',
  QUEUE_CALL_NEXT: 'queue:call_next',
  QUEUE_UPDATE_PRIORITY: 'queue:update_priority',
  QUEUE_ANALYTICS: 'queue:analytics',
  
  // Patient Management
  PATIENT_CREATE: 'patient:create',
  PATIENT_VIEW: 'patient:view',
  PATIENT_UPDATE: 'patient:update',
  PATIENT_DELETE: 'patient:delete',
  
  // Appointment Management
  APPOINTMENT_CREATE: 'appointment:create',
  APPOINTMENT_VIEW: 'appointment:view',
  APPOINTMENT_UPDATE: 'appointment:update',
  APPOINTMENT_DELETE: 'appointment:delete',
  
  // Billing
  INVOICE_CREATE: 'invoice:create',
  INVOICE_VIEW: 'invoice:view',
  PAYMENT_PROCESS: 'payment:process',
  
  // Laboratory
  LAB_ORDER: 'lab:order',
  LAB_RESULT: 'lab:result',
  
  // Reports
  REPORTS_VIEW: 'reports:view',
  ANALYTICS_VIEW: 'analytics:view'
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  
  [ROLES.ADMIN]: [
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.QUEUE_ANALYTICS,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW
  ],
  
  [ROLES.DOCTOR]: [
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.QUEUE_CALL_NEXT,
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.LAB_ORDER,
    PERMISSIONS.LAB_RESULT
  ],
  
  [ROLES.NURSE]: [
    PERMISSIONS.QUEUE_CHECK_IN,
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.QUEUE_UPDATE_PRIORITY,
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.LAB_ORDER
  ],
  
  [ROLES.RECEPTIONIST]: [
    PERMISSIONS.QUEUE_CHECK_IN,
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_UPDATE
  ],
  
  [ROLES.LAB_TECH]: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.LAB_ORDER,
    PERMISSIONS.LAB_RESULT
  ],
  
  [ROLES.BILLING]: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.PAYMENT_PROCESS,
    PERMISSIONS.REPORTS_VIEW
  ],
  
  [ROLES.PATIENT]: [
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.APPOINTMENT_VIEW
  ]
};
