export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  DOCTOR: 'doctor',
  NURSE: 'nurse',
  RECEPTIONIST: 'receptionist',
  LAB_TECH: 'lab_technician',
  BILLING: 'billing_staff',
  PATIENT: 'patient'
};

export const PERMISSIONS = {
  // Queue Management
  QUEUE_CHECK_IN: 'queue:check_in',
  QUEUE_VIEW: 'queue:view',
  QUEUE_CALL_NEXT: 'queue:call_next',
  QUEUE_UPDATE_PRIORITY: 'queue:update_priority',
  QUEUE_ANALYTICS: 'queue:analytics',

  // Patient Management
  PATIENT_CREATE: 'patient:create',
  PATIENT_VIEW: 'patient:view',
  PATIENT_UPDATE: 'patient:update',
  PATIENT_DELETE: 'patient:delete',

  // Doctor Management
  DOCTOR_CREATE: 'doctor:create',
  DOCTOR_VIEW: 'doctor:view',
  DOCTOR_UPDATE: 'doctor:update',
  DOCTOR_DELETE: 'doctor:delete',

  // Hospital Management
  HOSPITAL_CREATE: 'hospital:create',
  HOSPITAL_VIEW: 'hospital:view',
  HOSPITAL_UPDATE: 'hospital:update',
  HOSPITAL_DELETE: 'hospital:delete',

  // Department Management
  DEPARTMENT_CREATE: 'department:create',
  DEPARTMENT_VIEW: 'department:view',
  DEPARTMENT_UPDATE: 'department:update',
  DEPARTMENT_DELETE: 'department:delete',
  DEPARTMENT_MANAGE_STAFF: 'department:manage_staff',

  // User Management
  USER_VIEW: 'user:view',
  USER_CREATE: 'user:create',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  USER_MANAGE: 'user:manage',

  // Appointment Management
  APPOINTMENT_CREATE: 'appointment:create',
  APPOINTMENT_VIEW: 'appointment:view',
  APPOINTMENT_UPDATE: 'appointment:update',
  APPOINTMENT_DELETE: 'appointment:delete',

  // Billing
  INVOICE_CREATE: 'invoice:create',
  INVOICE_VIEW: 'invoice:view',
  PAYMENT_PROCESS: 'payment:process',

  // Laboratory
  LAB_ORDER: 'lab:order',
  LAB_RESULT: 'lab:result',
  LAB_MANAGE: 'lab:manage',

  // Reports
  REPORTS_VIEW: 'reports:view',
  ANALYTICS_VIEW: 'analytics:view',

  // Staff & HR
  STAFF_VIEW: 'staff:view',
  STAFF_MANAGE: 'staff:manage',

  // Cross-tenant record sharing (MPI)
  RECORD_SHARE_GRANT: 'record_share:grant',
  RECORD_SHARE_VIEW_EXTERNAL: 'record_share:view_external',

  // Facility profiles (laboratory / pharmacy)
  FACILITY_VIEW: 'facility:view',
  FACILITY_MANAGE: 'facility:manage',

  // Subscription plan catalogue (platform-level; SUPER_ADMIN only)
  PLAN_VIEW: 'plan:view',
  PLAN_MANAGE: 'plan:manage'
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.ADMIN]: [
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.QUEUE_ANALYTICS,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.DOCTOR_CREATE,
    PERMISSIONS.DOCTOR_VIEW,
    PERMISSIONS.DOCTOR_UPDATE,
    PERMISSIONS.HOSPITAL_VIEW,
    PERMISSIONS.HOSPITAL_UPDATE,
    PERMISSIONS.DEPARTMENT_CREATE,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.DEPARTMENT_UPDATE,
    PERMISSIONS.DEPARTMENT_MANAGE_STAFF,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.STAFF_MANAGE,
    PERMISSIONS.RECORD_SHARE_GRANT,
    PERMISSIONS.RECORD_SHARE_VIEW_EXTERNAL,
    PERMISSIONS.LAB_MANAGE,
    PERMISSIONS.FACILITY_VIEW,
    PERMISSIONS.FACILITY_MANAGE
  ],

  [ROLES.DOCTOR]: [
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.QUEUE_CALL_NEXT,
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.DOCTOR_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.LAB_ORDER,
    PERMISSIONS.LAB_RESULT,
    PERMISSIONS.RECORD_SHARE_VIEW_EXTERNAL
  ],

  [ROLES.NURSE]: [
    PERMISSIONS.QUEUE_CHECK_IN,
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.QUEUE_UPDATE_PRIORITY,
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.DOCTOR_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.LAB_ORDER
  ],

  [ROLES.RECEPTIONIST]: [
    PERMISSIONS.QUEUE_CHECK_IN,
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.DOCTOR_VIEW,
    PERMISSIONS.HOSPITAL_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_UPDATE
  ],

  [ROLES.LAB_TECH]: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.DOCTOR_VIEW,
    PERMISSIONS.LAB_ORDER,
    PERMISSIONS.LAB_RESULT,
    PERMISSIONS.LAB_MANAGE
  ],

  [ROLES.BILLING]: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.PAYMENT_PROCESS,
    PERMISSIONS.REPORTS_VIEW
  ],

  [ROLES.PATIENT]: [
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.DOCTOR_VIEW,
    PERMISSIONS.HOSPITAL_VIEW,
    PERMISSIONS.APPOINTMENT_VIEW
  ]
};
